#!/usr/bin/env bash
# Install nginx on my web01 server
# Configure nginx server to have a custom 404 page that contains
# "Ceci n'est pas une page"
sudo apt-get -y install nginx
new_string="	error_page 404 /error_404.html;"
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sudo sed -i "38i\\$new_string" /etc/nginx/sites-available/default
sudo service nginx start
