#!/usr/bin/env bash
# install HA proxy load balancer
sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8.\*
config="
frontend http
	bind *:80
	mode http
	default_backend servers

backend servers
	mode http
	balance roundrobin
	server 472920-web-01 18.207.112.170:80 check
	server 472920-web-02 100.27.12.171:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo systemctl enable haproxy
sudo service haproxy restart
