#!/usr/bin/env bash
# creates SQL dump and archive
if [ $# -ne 1 ]; then
	echo "Usage $0 <mysql_password>"
	exit 1
fi
mysqldump -u root -p "$1" --all-databases > backup.sql
DATE=$(date +'%d-%m-%Y')
tar czf "$DATE.tar.gz" backup.sql
