#!/usr/bin/env bash
# displays infinity and beyond indefinitely with 2 second sleeps
# 'I am invincible!!!' when receiving a SIGTERM signal
trap "echo I am invincible!!!" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
