#!/usr/bin/env bash
# change local host and facebook resolve
cp /etc/hosts ~/hostss
sudo sed -i 's/^127\.0\.0\.1/127.0.0.2/' ~/hostss
echo "8.8.8.8		facebook.com" >> ~/hostss

cp -f ~/hostss /etc/hosts
rm hostss
