#!/usr/bin/env bash
# Update Nginx configuration to run as nginx user
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

# Configure Nginx to listen on port 8080
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
